# ============================================================================
#  CRM with POS — make targets
#  Run `make help` for the full list.
# ============================================================================

SHELL := /bin/bash
.DEFAULT_GOAL := help

# --- Paths --------------------------------------------------------------------
BACKEND  := backend
FRONTEND := frontend
VENV     := $(BACKEND)/.venv

# --- Docker -------------------------------------------------------------------
COMPOSE      := docker compose
PROD_COMPOSE := docker compose --env-file .env.prod -f docker-compose.prod.yml

# Override at the CLI:  make docker-build REGISTRY=ghcr.io/me IMAGE_TAG=v1.2.3
REGISTRY  ?= ghcr.io/your-org
IMAGE_TAG ?= latest
# VITE_API_URL is baked into the frontend image at build time
VITE_API_URL ?= http://localhost:8000


# ============================================================================
#  help
# ============================================================================
.PHONY: help
help:  ## Show this help
	@awk 'BEGIN {FS = ":.*##"; \
		printf "\nUsage:\n  make \033[36m<target>\033[0m\n"} \
		/^[a-zA-Z0-9_-]+:.*?##/ { printf "  \033[36m%-22s\033[0m %s\n", $$1, $$2 } \
		/^##@/ { printf "\n\033[1m%s\033[0m\n", substr($$0, 5) }' $(MAKEFILE_LIST)


##@ Setup

.PHONY: install install-backend install-frontend
install: install-backend install-frontend  ## Install backend + frontend deps

install-backend:  ## Create venv, install Python deps, copy .env
	@test -d $(VENV) || python3 -m venv $(VENV)
	$(VENV)/bin/pip install --upgrade pip
	$(VENV)/bin/pip install -r $(BACKEND)/requirements.txt
	@test -f $(BACKEND)/.env || cp $(BACKEND)/.env.example $(BACKEND)/.env

install-frontend:  ## Install Node deps, copy .env
	cd $(FRONTEND) && npm install
	@test -f $(FRONTEND)/.env || cp $(FRONTEND)/.env.example $(FRONTEND)/.env


##@ Database

.PHONY: db-up db-down db-logs db-shell migrate migration seed seed-demo seed-fresh reset-db

db-up:  ## Start the Postgres container
	$(COMPOSE) up -d db

db-down:  ## Stop the Postgres container
	$(COMPOSE) stop db

db-logs:  ## Tail Postgres logs
	$(COMPOSE) logs -f db

db-shell:  ## Open a psql shell inside the container
	$(COMPOSE) exec db psql -U crm -d crm

migrate:  ## Apply all pending Alembic migrations
	cd $(BACKEND) && .venv/bin/alembic upgrade head

migration:  ## Generate a new autogenerated migration. Usage: make migration m="add foo"
	@test -n "$(m)" || (echo "Usage: make migration m=\"message\"" && exit 1)
	cd $(BACKEND) && .venv/bin/alembic revision --autogenerate -m "$(m)"

seed:  ## Insert the minimal seed: 1 tenant, 1 admin (idempotent)
	cd $(BACKEND) && .venv/bin/python -m app.seeds

seed-demo:  ## Insert the full demo dataset (2 tenants, users, orders, invoices, payments)
	cd $(BACKEND) && .venv/bin/python -m app.seeds --demo

seed-fresh:  ## WIPE all tenants and load the demo dataset (DESTRUCTIVE)
	@read -p "This wipes all tenant data. Continue? [y/N] " ans && [ "$$ans" = "y" ]
	cd $(BACKEND) && .venv/bin/python -m app.seeds --demo --reset

reset-db:  ## DROP the local DB volume and reseed (DESTRUCTIVE)
	@read -p "This destroys all local data. Continue? [y/N] " ans && [ "$$ans" = "y" ]
	$(COMPOSE) down -v
	$(COMPOSE) up -d db
	@echo "waiting for postgres..."; sleep 3
	$(MAKE) migrate
	$(MAKE) seed


##@ Dev

.PHONY: dev backend frontend

dev:  ## Run backend + frontend together (parallel, Ctrl-C stops both)
	@$(MAKE) -j 2 backend frontend

backend:  ## Run the FastAPI dev server with auto-reload
	cd $(BACKEND) && .venv/bin/uvicorn app.main:app --reload --host 0.0.0.0 --port 8000

frontend:  ## Run the Vite dev server
	cd $(FRONTEND) && npm run dev


##@ Quality

.PHONY: lint typecheck test test-backend test-frontend

lint: typecheck  ## Run all lint/type checks

typecheck:  ## TypeScript type-check (frontend)
	cd $(FRONTEND) && npm run lint

test: test-backend test-frontend  ## Run all tests

test-backend:  ## Run backend tests (pytest)
	@if [ -d $(BACKEND)/tests ]; then \
		cd $(BACKEND) && .venv/bin/python -m pytest -q; \
	else \
		echo "No backend tests yet. Add them under $(BACKEND)/tests/."; \
	fi

test-frontend:  ## Run frontend tests (vitest)
	@if grep -q '"test"' $(FRONTEND)/package.json; then \
		cd $(FRONTEND) && npm test; \
	else \
		echo "No frontend tests yet. Add vitest and a 'test' script in $(FRONTEND)/package.json."; \
	fi


##@ Build

.PHONY: build build-frontend

build: build-frontend  ## Build production artifacts

build-frontend:  ## Build the frontend bundle into frontend/dist
	cd $(FRONTEND) && npm run build


##@ Docker images

.PHONY: docker-build docker-build-backend docker-build-frontend docker-push

docker-build: docker-build-backend docker-build-frontend  ## Build both Docker images

docker-build-backend:  ## Build the backend image
	docker build -t $(REGISTRY)/crm-backend:$(IMAGE_TAG) -f $(BACKEND)/Dockerfile $(BACKEND)

docker-build-frontend:  ## Build the frontend image (bakes VITE_API_URL)
	docker build \
		--build-arg VITE_API_URL=$(VITE_API_URL) \
		-t $(REGISTRY)/crm-frontend:$(IMAGE_TAG) \
		-f $(FRONTEND)/Dockerfile $(FRONTEND)

docker-push: docker-build  ## Build then push both images to $(REGISTRY)
	docker push $(REGISTRY)/crm-backend:$(IMAGE_TAG)
	docker push $(REGISTRY)/crm-frontend:$(IMAGE_TAG)


##@ Deploy

.PHONY: deploy-up deploy-down deploy-restart deploy-logs deploy-migrate deploy-seed deploy-pull deploy-ps

deploy-up:  ## Bring up the production stack (uses .env.prod + docker-compose.prod.yml)
	@test -f .env.prod || (echo "Missing .env.prod — copy from .env.prod.example first" && exit 1)
	$(PROD_COMPOSE) up -d

deploy-down:  ## Stop and remove the production stack (volumes are preserved)
	$(PROD_COMPOSE) down

deploy-restart:  ## Recreate containers after pulling new images
	$(PROD_COMPOSE) up -d --force-recreate

deploy-logs:  ## Tail logs from the production stack
	$(PROD_COMPOSE) logs -f --tail=200

deploy-migrate:  ## Run Alembic migrations inside the deployed backend container
	$(PROD_COMPOSE) exec backend alembic upgrade head

deploy-seed:  ## Run the seed script inside the deployed backend (first deploy only)
	$(PROD_COMPOSE) exec backend python -m app.seeds

deploy-pull:  ## Pull latest images from the registry
	$(PROD_COMPOSE) pull

deploy-ps:  ## Show running production containers
	$(PROD_COMPOSE) ps


##@ Maintenance

.PHONY: clean clean-venv clean-frontend clean-pyc

clean: clean-venv clean-frontend  ## Remove venv, node_modules, build artifacts, caches

clean-venv:  ## Remove the Python venv and bytecode caches
	rm -rf $(VENV)
	$(MAKE) clean-pyc

clean-pyc:  ## Remove __pycache__ and .pytest_cache under backend/
	find $(BACKEND) -type d \( -name __pycache__ -o -name .pytest_cache \) -prune -exec rm -rf {} +

clean-frontend:  ## Remove node_modules and the dist/ build
	rm -rf $(FRONTEND)/node_modules $(FRONTEND)/dist
